# Config for polar worlds
default:
  autosaveIntervalTicks: -1 # -1 to disable
  announceAutosave: true
  time: 1000
  saveOnStop: false
  loadOnStartup: true
  spawn: 0.0, 64.0, 0.0, 0.0, 0.0
  worldRadiusBlocks: 570 # Circular radius around spawn; blocks and entities outside it are discarded
  difficulty: NORMAL
  async: false
  saveLight: true # Whether chunks are saved with light data. Reduces load time and CPU usage while loading but increases world size
  compression: ZSTD # One of: ZSTD, NONE
  compressionLevel: 7 # ZSTD compression level, higher means smaller file size but longer save times. Max 22, default 7
  worldType: FLAT # One of: NORMAL, FLAT, AMPLIFIED, LARGE_BIOMES
  environment: NORMAL # One of: NORMAL, NETHER, THE_END, CUSTOM
  gamerules: # Custom rules: liquidPhysics, blockPhysics, blockGravity, blockFade
    - spawn_mobs: false
    - fire_spread_radius_around_player: 0
    - random_tick_speed: 0
    - mob_griefing: false
    - spread_vines: false
    - tnt_explodes: false
    - blockFade: false
    - blockPhysics: true
    - blockGravity: true
    - liquidPhysics: true
worlds:
  #worldOne:
    #...
  #worldTwo:
    #...
